import { Inter, Roboto, Open_Sans } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
}); // Specify the weight
const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Techspance",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <NavigationBar />
        {/* <div className="navigation-offset mt-24"></div> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
