export const data = {
  success: true,
  data: [
    {
      _id: "6720f2a5da942f784a103fd8",
      name: "David Kim",
      title: "UX/UI Designer",
      image: "",
      bio: "David is a talented UX/UI designer who focuses on creating user-friendly and visually appealing interfaces. He loves to enhance user experiences through design.",
      social_link: {
        facebook: "https://facebook.com/davidkim",
        linkedin: "https://linkedin.com/in/davidkim",
        github: "https://github.com/davidkim",
      },
    },
    {
      _id: "6720f2a5da942f784a103fd7",
      name: "Catherine Lee",
      title: "Backend Developer",
      image: "",
      bio: "Catherine is a backend developer with a passion for databases and server-side logic. She ensures that applications run smoothly behind the scenes.",
      social_link: {
        facebook: "https://facebook.com/catherinelee",
        linkedin: "https://linkedin.com/in/catherinelee",
        github: "https://github.com/catherinelee",
      },
    },
    {
      _id: "6720f2a5da942f784a103fdd",
      name: "Isabella Martinez",
      title: "Quality Assurance Engineer",
      image: "",
      bio: "Isabella is a quality assurance engineer dedicated to maintaining high standards in software development through rigorous testing.",
      social_link: {
        facebook: "https://facebook.com/isabellamartinez",
        linkedin: "https://linkedin.com/in/isabellamartinez",
        github: "https://github.com/isabellamartinez",
      },
    },
    {
      _id: "6720f2a5da942f784a103fdb",
      name: "Grace O'Connor",
      title: "Marketing Specialist",
      image: "",
      bio: "Grace is a marketing specialist with expertise in digital marketing strategies. She enjoys creating campaigns that resonate with target audiences.",
      social_link: {
        facebook: "https://facebook.com/graceoconnor",
        linkedin: "https://linkedin.com/in/graceoconnor",
        github: "https://github.com/graceoconnor",
      },
    },
    {
      _id: "6720f2a5da942f784a103fd6",
      name: "Bob Smith",
      title: "Frontend Developer",
      image: "",
      bio: "Bob is a creative frontend developer who specializes in building responsive and engaging user interfaces. He enjoys coding and exploring new technologies.",
      social_link: {
        facebook: "https://facebook.com/bobsmith",
        linkedin: "https://linkedin.com/in/bobsmith",
        github: "https://github.com/bobsmith",
      },
    },
    {
      _id: "6720f2a5da942f784a103fd5",
      name: "Alice Johnson",
      title: "Project Manager",
      image: "",
      bio: "Alice is an experienced project manager with a knack for delivering results on time and within budget. She loves organizing teams and ensuring smooth workflows.",
      social_link: {
        facebook: "https://facebook.com/alicejohnson",
        linkedin: "https://linkedin.com/in/alicejohnson",
        github: "https://github.com/alicejohnson",
      },
    },
    {
      _id: "6720f2a5da942f784a103fdc",
      name: "Henry Garcia",
      title: "Content Writer",
      image: "",
      bio: "Henry is a content writer who crafts compelling narratives and informative articles. He enjoys writing about technology and innovation.",
      social_link: {
        facebook: "https://facebook.com/henrygarcia",
        linkedin: "https://linkedin.com/in/henrygarcia",
        github: "https://github.com/henrygarcia",
      },
    },
    {
      _id: "6720f2a5da942f784a103fda",
      name: "Frank White",
      title: "Data Scientist",
      image: "",
      bio: "Frank is a data scientist with a strong analytical background. He loves extracting insights from data to drive business decisions.",
      social_link: {
        facebook: "https://facebook.com/frankwhite",
        linkedin: "https://linkedin.com/in/frankwhite",
        github: "https://github.com/frankwhite",
      },
    },
    {
      _id: "6720f2a5da942f784a103fde",
      name: "Jack Thompson",
      title: "Business Analyst",
      image: "",
      bio: "Jack is a business analyst who helps organizations understand their needs and develop solutions that align with their goals.",
      social_link: {
        facebook: "https://facebook.com/jackthompson",
        linkedin: "https://linkedin.com/in/jackthompson",
        github: "https://github.com/jackthompson",
      },
    },
    {
      _id: "6720f2a5da942f784a103fd9",
      name: "Eva Patel",
      title: "DevOps Engineer",
      image: "",
      bio: "Eva is a skilled DevOps engineer who bridges the gap between development and operations, ensuring efficient deployment and system performance.",
      social_link: {
        facebook: "https://facebook.com/evapatel",
        linkedin: "https://linkedin.com/in/evapatel",
        github: "https://github.com/evapatel",
      },
    },
  ],
};